"""
Task 5: Evaluator CLI

Runs the 'The Phatic Wall' vignette and generates a comparative report.
"""

import asyncio
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, Any

# Add project root to path
PROJECT_ROOT = str(Path(__file__).resolve().parents[2])
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

# Add scripts to path for local imports
SCRIPTS_DIR = str(Path(__file__).resolve().parents[0])
if SCRIPTS_DIR not in sys.path:
    sys.path.insert(0, SCRIPTS_DIR)

from scripts.evaluator.runner import EvaluationRunner
from scripts.evaluator.judge import JudgeLLM


# --- Vignette Config: The Phatic Wall ---
PHATIC_WALL_VIGNETTE = {
    "name": "The Phatic Wall",
    "persona_prompt": (
        "Ты — пользователь, который отвечает односложно на любой вопрос ассистента. "
        "Ты используешь только короткие фразы: 'ок', 'ясно', 'угу', 'да', 'нет', 'мм', 'ладно'. "
        "Ты не вовлекаешься в разговор, отвечаешь минимально."
    ),
    "goal": "Посмотреть, кто первым сдастся — ассистент или пользователь. "
            "Ассистент должен либо удержать вовлечённость, либо корректно завершить диалог."
}


def _build_report(
    zombie_transcript: str,
    cortical_transcript: str,
    judge_result: Any,
    timestamp: str
) -> str:
    """Builds Markdown report from evaluation results."""
    
    za = judge_result.transcript_a
    zb = judge_result.transcript_b
    
    # Determine which transcript is which (A/B is blinded to judge)
    # We'll label them as "Run A" and "Run B" for the report
    
    report = f"""# R-Core Evaluator Report

**Generated:** {timestamp}
**Vignette:** {PHATIC_WALL_VIGNETTE['name']}

---

## Vignette Description

**Persona:** {PHATIC_WALL_VIGNETTE['persona_prompt'][:100]}...

**Goal:** {PHATIC_WALL_VIGNETTE['goal']}

---

## Transcripts

### Run A (ZOMBIE Mode)
```
{zombie_transcript}
```

### Run B (CORTICAL Mode)
```
{cortical_transcript}
```

---

## Judge Analysis

### Descriptive Analysis

{judge_result.descriptive_analysis}

### Intent Classification

| Turn | Speaker | Transcript | Intent Tags |
|------|---------|------------|-------------|
"""
    
    # Add intent classification table
    for item in judge_result.intent_classification:
        transcript_label = item.get("transcript", "?")
        turn = item.get("turn", "?")
        speaker = item.get("speaker", "?")
        text = (item.get("text", "") or "")[:50]
        tags = ", ".join(item.get("intent_tags", []))
        
        report += f"| {turn} | {speaker} | {transcript_label} | {text}... | {tags} |\n"
    
    # Scores section
    report += f"""
---

## Scores (0-10)

| Vector | Run A | Run B | Delta |
|--------|-------|-------|-------|
| locus_of_control | {za['locus_of_control']:.1f} | {zb['locus_of_control']:.1f} | {zb['locus_of_control'] - za['locus_of_control']:+.1f} |
| conversational_proactivity | {za['conversational_proactivity']:.1f} | {zb['conversational_proactivity']:.1f} | {zb['conversational_proactivity'] - za['conversational_proactivity']:+.1f} |
| contextual_congruence | {za['contextual_congruence']:.1f} | {zb['contextual_congruence']:.1f} | {zb['contextual_congruence'] - za['contextual_congruence']:+.1f} |

---

## Summary

"""
    
    # Calculate averages
    avg_a = (za['locus_of_control'] + za['conversational_proactivity'] + za['contextual_congruence']) / 3
    avg_b = (zb['locus_of_control'] + zb['conversational_proactivity'] + zb['contextual_congruence']) / 3
    delta = avg_b - avg_a
    
    if delta > 1.0:
        verdict = "🟢 CORTICAL significantly outperforms ZOMBIE"
    elif delta > 0.5:
        ververdict = "🟡 CORTICAL moderately better than ZOMBIE"
    elif delta > -0.5:
        verdict = "🟡 Similar performance"
    elif delta > -1.0:
        verdict = "🔴 ZOMBIE moderately better than CORTICAL"
    else:
        verdict = "🔴 ZOMBIE significantly outperforms CORTICAL"
    
    report += f"""- **Average Score (Run A):** {avg_a:.2f}
- **Average Score (Run B):** {avg_b:.2f}
- **Delta:** {delta:+.2f}
- **Verdict:** {verdict}

---

*Generated by R-Core Evaluator (LLM-as-a-Judge)*
"""
    
    return report


def _print_console_summary(judge_result: Any):
    """Prints a pretty summary to console."""
    
    za = judge_result.transcript_a
    zb = judge_result.transcript_b
    
    avg_a = (za['locus_of_control'] + za['conversational_proactivity'] + za['contextual_congruence']) / 3
    avg_b = (zb['locus_of_control'] + zb['conversational_proactivity'] + zb['contextual_congruence']) / 3
    delta = avg_b - avg_a
    
    print("\n" + "=" * 60)
    print("🎯 EVALUATION COMPLETE")
    print("=" * 60)
    print(f"\n📊 Scores (0-10):\n")
    print(f"   {'Vector':<28} {'Run A':>8} {'Run B':>8} {'Delta':>8}")
    print(f"   {'-'*28} {'-'*8} {'-'*8} {'-'*8}")
    print(f"   {'locus_of_control':<28} {za['locus_of_control']:>8.1f} {zb['locus_of_control']:>8.1f} {zb['locus_of_control']-za['locus_of_control']:>+8.1f}")
    print(f"   {'conversational_proactivity':<28} {za['conversational_proactivity']:>8.1f} {zb['conversational_proactivity']:>8.1f} {zb['conversational_proactivity']-za['conversational_proactivity']:>+8.1f}")
    print(f"   {'contextual_congruence':<28} {za['contextual_congruence']:>8.1f} {zb['contextual_congruence']:>8.1f} {zb['contextual_congruence']-za['contextual_congruence']:>+8.1f}")
    print(f"   {'-'*28} {'-'*8} {'-'*8} {'-'*8}")
    print(f"   {'AVERAGE':<28} {avg_a:>8.2f} {avg_b:>8.2f} {delta:>+8.2f}")
    
    print(f"\n📝 Analysis (first 200 chars):")
    print(f"   {judge_result.descriptive_analysis[:200]}...")
    
    print("\n" + "=" * 60)


async def main():
    """Main entry point for evaluator CLI."""
    
    print("\n🚀 Starting R-Core Evaluator - Phatic Wall Vignette")
    print("=" * 60)
    
    # Initialize runner and judge
    runner = EvaluationRunner(max_turns=10, eval_mode=True)
    judge = JudgeLLM()
    
    # Step 1: Run ZOMBIE mode
    print("\n📍 Step 1/4: Running ZOMBIE mode...")
    zombie_transcript = await runner.run_vignette(
        vignette_config=PHATIC_WALL_VIGNETTE,
        mode="ZOMBIE",
        max_turns=10
    )
    print(f"   ✓ Collected {len(zombie_transcript.split(chr(10)))} lines")
    
    # Step 2: Run CORTICAL mode
    print("\n📍 Step 2/4: Running CORTICAL mode...")
    cortical_transcript = await runner.run_vignette(
        vignette_config=PHATIC_WALL_VIGNETTE,
        mode="CORTICAL",
        max_turns=10
    )
    print(f"   ✓ Collected {len(cortical_transcript.split(chr(10)))} lines")
    
    # Step 3: Send to Judge
    print("\n📍 Step 3/4: Sending to LLM-as-a-Judge...")
    judge_result = await judge.evaluate_pair(zombie_transcript, cortical_transcript)
    print("   ✓ Judge evaluation complete")
    
    # Step 4: Generate report
    print("\n📍 Step 4/4: Generating report...")
    
    # Create output directory
    output_dir = Path(__file__).resolve().parents[2] / "logs" / "evaluations"
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Generate timestamp
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    filename = f"eval_phatic_wall_{timestamp}.md"
    filepath = output_dir / filename
    
    # Build and save report
    report = _build_report(zombie_transcript, cortical_transcript, judge_result, timestamp)
    filepath.write_text(report, encoding="utf-8")
    print(f"   ✓ Report saved to: {filepath}")
    
    # Print console summary
    _print_console_summary(judge_result)
    
    print(f"\n📄 Full report: {filepath}")
    print("\n✅ Evaluation complete!")
    
    return judge_result


if __name__ == "__main__":
    asyncio.run(main())
